server {
    listen 80;
    server_name localhost; # หรือใส่โดเมนของคุณ

    # ตั้งให้ root เป็นตำแหน่งไฟล์ build (dist) ของคุณ
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
